spring:
  application:
    name: rag-alura

  datasource:
    url: jdbc:postgresql://localhost:5432/rag_db
    username: postgres
    password: postgrespassword
    driver-class-name: org.postgresql.Driver

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2
          temperature: 0.2
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768
        initialize-schema: true

server:
  port: 8080